import VocabDeck, { toCards as toVocabCards } from "./VocabDeck.mjs";
import KanjiDeck, { toCards as toKanjiCards } from "./KanjiDeck.mjs";

// common

const CardType = {
    Vocab: 0,
    Kanji: 1
};

let searchType = CardType.Vocab;

const e_search = document.querySelector("#search")
e_search.addEventListener("keydown", (e) => {
    if (e.key === "Enter")
        search();
});

const b_go = document.querySelector("#go")
b_go.addEventListener("click", search);

let loading = false;

async function search() {
    if (loading) return;
    loading = true;
    list.innerHTML = "Loading..."
    
    const term = e_search.value;

    await (async function() {
        switch (searchType) {
            case CardType.Vocab:
                await searchVocab(term);
                break;
            case CardType.Kanji:
                await searchKanji(term);
                break;
        }
    })()
    .catch(() => {
        list.innerHTML = "Error- Please try again."
    });
    
    loading = false;
}

const e_list = document.querySelector("#list")
e_list.addEventListener("click", (e) => {
    switch (searchType) {
        case CardType.Vocab:
            vocabDeck.clicked(e)
            break;
        case CardType.Kanji:
            kanjiDeck.clicked(e)
            break;
    }
});

// vocab

const vocabDeck = new VocabDeck();

const b_vocab = document.querySelector("#vocab")
b_vocab.addEventListener("click", (e) => {
    searchType = CardType.Vocab;
    search();
});

async function searchVocab(term) {
    vocabDeck.clearCache();
    
    const url = `https://jisho.org/api/v1/search/words?keyword=${term}`;
    const comp = encodeURIComponent(url);
    await fetch(`https://api.codetabs.com/v1/proxy?quest=${comp}`)
        .then(response => response.json())
        .then(results => e_list.innerHTML = vocabDeck.render(toVocabCards(results.data)));
}

// kanji

let engToKanji = { };
fetch("../json/kanji-by-meaning.json")
    .then(response => response.json())
    .then(json => engToKanji = json);

const kanjiDeck = new KanjiDeck();

const b_kanji = document.querySelector("#kanji")
b_kanji.addEventListener("click", (e) => {
    searchType = CardType.Kanji;
    search();
});

async function searchKanji(term) {
    kanjiDeck.clearCache();
    
    term = term.toLowerCase();
    const matches = Object.keys(engToKanji).filter(key => key.toLowerCase().includes(term))
    matches.sort((a, b) => { // sort algorithm generated by ChatGPT
        const aLower = a.toLowerCase();
        const bLower = b.toLowerCase();

        if (aLower === term && bLower !== term) return -1;
        if (bLower === term && aLower !== term) return 1;

        const aIndex = aLower.indexOf(term);
        const bIndex = bLower.indexOf(term);
        if (aIndex !== bIndex) return aIndex - bIndex;

        return a.length - b.length;
    });
    const kanjiList = matches.flatMap(key => engToKanji[key]);
    
    const fetchPromises = kanjiList.map(async kanji => {
        const response = await fetch(`https://kanjiapi.dev/v1/kanji/${encodeURIComponent(kanji)}`);
        const results = await response.json();
        return results;
    });
    const cardList = await Promise.all(fetchPromises);
    
    e_list.innerHTML = kanjiDeck.render(toKanjiCards(cardList));
}