import VocabDeck, { toCards as toVocabCards } from "./VocabDeck.mjs";
import KanjiDeck, { toCards as toKanjiCards } from "./KanjiDeck.mjs";

// common

const CardType = {
    Vocab: 0,
    Kanji: 1
};

let searchType = CardType.Vocab;

const e_search = document.querySelector("#search")
// note- event (4/5)
e_search.addEventListener("keydown", (e) => {
    if (e.key === "Enter")
        search();
});

const b_go = document.querySelector("#go")
// note- event (5/5)
b_go.addEventListener("click", search);

let loading = false;

async function search() {
    if (loading) return;
    loading = true;
    list.innerHTML = "Loading..."
    
    const term = e_search.value;
    if (!term) {
        loading = false;
        list.innerHTML = "Please enter a search term."
        return;
    }

    await (async function() {
        switch (searchType) {
            case CardType.Vocab:
                await searchVocab(term);
                break;
            case CardType.Kanji:
                await searchKanji(term);
                break;
        }
    })()
    .catch(() => {
        list.innerHTML = "Error- Please try again."
    });
    
    loading = false;
}

const e_label = document.querySelector("#label");
function updateLabel() {
    switch (searchType) {
        case CardType.Vocab:
            e_label.textContent = "Vocabulary";
            break;
        case CardType.Kanji:
            e_label.textContent = "Kanji";
            break;
    }
}
updateLabel();

const e_list = document.querySelector("#list")
// note- event (6/5)
e_list.addEventListener("click", (e) => {
    switch (searchType) {
        case CardType.Vocab:
            vocabDeck.clicked(e)
            break;
        case CardType.Kanji:
            kanjiDeck.clicked(e)
            break;
    }
});

// vocab

const vocabDeck = new VocabDeck();

const b_vocab = document.querySelector("#vocab")
// note- event (7/5)
b_vocab.addEventListener("click", () => {
    if (loading) return;
    searchType = CardType.Vocab;
    updateLabel();
    search();
});

async function searchVocab(term) {
    vocabDeck.clearCache();
    
    // note- endpoint (1/2)
    const url = `https://jisho.org/api/v1/search/words?keyword=${term}`;
    const comp = encodeURIComponent(url);
    // note- json
    // jisho's API normally conflicts with the browser's CORS policy when used on frontend; this bypasses that. thanks to chatgpt
    await fetch(`https://api.codetabs.com/v1/proxy?quest=${comp}`)
        .then(response => response.json())
        .then(results => e_list.innerHTML = vocabDeck.render(toVocabCards(results.data)));
}

// kanji

let engToKanji = { };
// note- json
fetch("./json/kanji-by-meaning.json")
    .then(response => response.json())
    .then(json => engToKanji = json);

const kanjiDeck = new KanjiDeck();

const b_kanji = document.querySelector("#kanji")
// note- event (8/5)
b_kanji.addEventListener("click", () => {
    if (loading) return;
    searchType = CardType.Kanji;
    updateLabel();
    search();
});

async function searchKanji(term) {
    kanjiDeck.clearCache();
    
    let kanjiList = [];

    if (isKanji(term[0])) {
        kanjiList = [term];
    }
    else {
        term = term.toLowerCase();
        const matches = Object.keys(engToKanji).filter(key => key.toLowerCase().includes(term))
        matches.sort((a, b) => { // sort algorithm generated by ChatGPT
            const aLower = a.toLowerCase();
            const bLower = b.toLowerCase();

            if (aLower === term && bLower !== term) return -1;
            if (bLower === term && aLower !== term) return 1;

            const aIndex = aLower.indexOf(term);
            const bIndex = bLower.indexOf(term);
            if (aIndex !== bIndex) return aIndex - bIndex;

            return a.length - b.length;
        });
        kanjiList = matches.flatMap(key => engToKanji[key]);
    }
    
    const fetchPromises = kanjiList.map(async kanji => {
        // note- endpoint (2/2)
        const response = await fetch(`https://kanjiapi.dev/v1/kanji/${encodeURIComponent(kanji)}`);
        // note- json
        const results = await response.json();
        return results;
    });
    const cardList = await Promise.all(fetchPromises);
    
    e_list.innerHTML = kanjiDeck.render(toKanjiCards(cardList));
}

function isKanji(char) { // kanji check by ChatGPT
  const code = char.charCodeAt(0);
  return ((code >= 0x4E00 && code <= 0x9FFF)
    || (code >= 0x3400 && code <= 0x4DBF));
}
