import xml.etree.ElementTree as ET
import json

# generated by ChatGPT with minor modifications

NAME = "kanji_by_meaning"

tree = ET.parse("kanjidic2.xml")
root = tree.getroot()

meaning_to_kanji = {}

for char in root.findall("character"):
    literal = char.find("literal").text

    for meaning in char.findall("./reading_meaning/rmgroup/meaning"):
        if "m_lang" in meaning.attrib and meaning.attrib["m_lang"] != "en":
            continue

        eng = meaning.text.strip()
        meaning_to_kanji.setdefault(eng, []).append(literal)

with open(f"{NAME}.json", "w", encoding="utf-8") as f:
    json.dump(meaning_to_kanji, f, ensure_ascii=False, indent=2)

print(F"Done! Dictionary saved to {NAME}.json")